export const USER_CREATE_SUCCESS = 'USER_CREATE_SUCCESS';
export const USER_CREATE_FAILED = 'USER_CREATE_FAILED';
export const FETCH_LIST_SUCCESS = 'FETCH_LIST_SUCCESS';
export const FETCH_LIST_FAILED = 'FETCH_LIST_FAILED';
export const FETCH_USER_LIST_SUCCESS = 'FETCH_USER_LIST_SUCCESS';
export const FETCH_USER_LIST_FAILED = 'FETCH_USER_LIST_FAILED';
export const FETCH_TABLE_COLUMNS_SUCCESS = 'FETCH_TABLE_COLUMNS_SUCCESS';
export const FETCH_TABLE_COLUMNS_FAILED = 'FETCH_TABLE_COLUMNS_FAILED';
export const FETCH_LOCALE_LIST_SUCCESS = 'FETCH_USER_LIST_SUCCESS';
export const FETCH_LOCALE_LIST_FAILED = 'FETCH_USER_LIST_FAILED';
export const RELOAD_FORM_FOR_EDIT = 'RELOAD_FORM_FOR_EDIT';

