//role _ resources _request
export const CREATE_ROLE_REQUEST = 'CREATE_ROLE_REQUEST';
export const CREATE_ROLE_SUCCESS = 'CREATE_ROLE_SUCCESS';
export const CREATE_ROLE_FAILURE = 'CREATE_ROLE_FAILURE';

//role _ resources _request
export const ROLE_RESOURCES_REQUEST  = 'ROLE_RESOURCES_REQUEST';
export const ROLE_RESOURCES_SUCCESS  = 'ROLE_RESOURCES_SUCCESS';
export const ROLE_RESOURCES_FAILURE  = 'ROLE_RESOURCES_FAILURE';

//role_scopes_data
export const ROLE_SCOPES_SUCCESS  = 'ROLE_SCOPES_SUCCESS';
export const ROLE_SCOPES_FAILURE  = 'ROLE_SCOPES_FAILURE';

//role_selected_scopes
export const ROLE_SELECTED_SCOPES = 'ROLE_SELECTED_SCOPES';
export const ROLE_RESET_SCOPES = 'ROLE_RESET_SCOPES';  

//role_selected_resources
export const ROLE_SELECTED_RESOURCES = 'ROLE_SELECTED_RESOURCES';
export const ROLE_RESET_RESOURCES = 'ROLE_RESET_RESOURCES';  

//role_record
export const GET_ROLES_RECORDS_SUCCESS  = 'GET_ROLES_RECORDS_SUCCESS';
export const GET_ROLES_RECORDS_FAILURE  = 'GET_ROLES_RECORDS_FAILURE';

//role_EDIT FORM DATA
export const SET_ROLE_EDIT_FORM_DATA  = 'SET_ROLE_EDIT_FORM_DATA';
export const HIDE_SCOPE_TREE_COMPONENT = 'HIDE_SCOPE_TREE_COMPONENT';
export const HIDE_RESOURCES_TREE_COMPONENT = 'HIDE_RESOURCES_TREE_COMPONENT';


//role_update role 
export const UPDATE_ROLE_SUCCESS  = 'UPDATE_ROLE_SUCCESS';
export const UPDATE_ROLE_FAILURE  = 'UPDATE_ROLE_FAILURE';

